name: Build and Release Caddy

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build and Release Caddy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: stable

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y jq curl git

    - name: Initialize Go module
      run: |
        mkdir -p build
        cd build
        go mod init caddy-build
        go get github.com/caddyserver/caddy/v2@latest
        cd ..


    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: go-mod-${{ runner.os }}-${{ hashFiles('build/go.sum') }}
        restore-keys: |
          go-mod-${{ runner.os }}-

    - name: Install xcaddy
      run: |
        go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
        echo "$HOME/go/bin" >> $GITHUB_PATH

    - name: Get latest Caddy version
      id: get_version
      run: |
        VERSION=$(curl -s https://api.github.com/repos/caddyserver/caddy/releases/latest | jq -r .tag_name)
        echo "version=$VERSION" >> $GITHUB_ENV

    - name: Build amd64
      run: |
        ARCH=amd64
        xcaddy build ${{ env.version }} \
          --output caddy-${ARCH}-${{ env.version }} \
          --with github.com/caddyserver/forwardproxy@caddy2=github.com/klzgrad/forwardproxy@naive
        tar -czvf caddy-${ARCH}-${{ env.version }}.tar.gz caddy-${ARCH}-${{ env.version }}

    - name: Build arm64
      env:
        GOOS: linux
        GOARCH: arm64
      run: |
        ARCH=arm64
        xcaddy build ${{ env.version }} \
          --output caddy-${ARCH}-${{ env.version }} \
          --with github.com/caddyserver/forwardproxy@caddy2=github.com/klzgrad/forwardproxy@naive
        tar -czvf caddy-${ARCH}-${{ env.version }}.tar.gz caddy-${ARCH}-${{ env.version }}

    - name: Generate SHA256 checksums
      run: |
        sha256sum caddy-amd64-${{ env.version }}.tar.gz > caddy-amd64-${{ env.version }}.sha256
        sha256sum caddy-arm64-${{ env.version }}.tar.gz > caddy-arm64-${{ env.version }}.sha256

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        body: |
          ### caddy-forwardproxy-naïve
        files: |
          caddy-amd64-${{ env.version }}.tar.gz
          caddy-arm64-${{ env.version }}.tar.gz
          caddy-amd64-${{ env.version }}.sha256
          caddy-arm64-${{ env.version }}.sha256
