name: Daily Check and Build Caddy

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  c:
    runs-on: ubuntu-latest
    outputs:
      o: ${{ steps.s.outputs.o }}
      t: ${{ steps.s.outputs.t }}
      v: ${{ steps.s.outputs.v }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - id: l
      run: echo "t=$(curl -s https://api.github.com/repos/caddyserver/caddy/releases/latest | jq -r .tag_name)" >> $GITHUB_OUTPUT
    - id: c
      run: |
        if git tag | grep -q .; then
          echo "t=$(git tag | sort -V | tail -n1)"
        else
          echo "t=none"
        fi >> $GITHUB_OUTPUT
    - id: s
      run: |
        l="${{ steps.l.outputs.t }}"
        c="${{ steps.c.outputs.t }}"
        echo "Latest: $l"
        echo "Current: $c"
        
        if [ "$l" != "$c" ]; then
          if ! git ls-remote --tags origin | grep -q "refs/tags/$l"; then
            git config user.name github-actions
            git config user.email github-actions@users.noreply.github.com
            git tag "$l"
            git push origin "$l"
          else
            echo "Tag $l already exists remotely, skipping tag creation"
          fi
          echo "t=$l" >> $GITHUB_OUTPUT
          echo "v=${l#v}" >> $GITHUB_OUTPUT
          echo "o=1" >> $GITHUB_OUTPUT
        else
          echo "o=0" >> $GITHUB_OUTPUT
        fi

  b:
    needs: c
    if: needs.c.outputs.o == '1'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        a: [amd64, arm64]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: stable
        cache: false
    - run: |
        go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
    - run: |
        GOOS=linux GOARCH=${{ matrix.a }} xcaddy build ${{ needs.c.outputs.t }} \
          --with github.com/caddyserver/forwardproxy@caddy2=github.com/klzgrad/forwardproxy@naive
        test -f caddy && chmod +x caddy || (echo "Caddy build failed" && exit 1)
        tar -czvf caddy_${{ needs.c.outputs.v }}_linux_${{ matrix.a }}.tar.gz caddy
        sha256sum caddy_${{ needs.c.outputs.v }}_linux_${{ matrix.a }}.tar.gz > caddy_${{ needs.c.outputs.v }}_linux_${{ matrix.a }}.sha256
    - uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ needs.c.outputs.t }}
        name: ${{ needs.c.outputs.t }}
        body: |
          ### caddy-forwardproxy-naïve
        files: |
          caddy_${{ needs.c.outputs.v }}_linux_${{ matrix.a }}.tar.gz
          caddy_${{ needs.c.outputs.v }}_linux_${{ matrix.a }}.sha256