name: Build and Release Caddy

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  build:
    name: Build and Release Caddy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Update Workflow Run Title
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RUN_ID: ${{ github.run_id }}
        CUSTOM_TITLE: 'Automated Caddy Deployment'
      run: |
        echo "Debug: CUSTOM_TITLE is set to $CUSTOM_TITLE"
        echo "Debug: RUN_ID is $RUN_ID"
        echo "Debug: Repository is ${{ github.repository }}"
        echo "Debug: Full API URL is https://api.github.com/repos/${{ github.repository }}/actions/runs/$RUN_ID"
        echo "Debug: Sending API request to update title..."
        for attempt in {1..3}; do
          echo "Attempt $attempt of 3..."
          response=$(curl -X PATCH \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/runs/$RUN_ID \
            -d "{\"name\": \"$CUSTOM_TITLE\"}" \
            -w "%{http_code}" \
            -o response.json \
            -s)
          echo "HTTP Status: $response"
          if [ "$response" -eq 200 ]; then
            echo "Title updated successfully!"
            break
          else
            echo "Failed to update title, response:"
            cat response.json
            if [ $attempt -lt 3 ]; then
              wait_time=$((attempt * 3))  # 动态等待：第一次 3 秒，第二次 6 秒
              echo "Retrying in $wait_time seconds..."
              sleep $wait_time
            else
              echo "Max retries reached, giving up."
            fi
          fi
        done
        echo "Debug: API request completed."

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: stable
        cache: false

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y jq curl git

    - name: Initialize Go module
      run: |
        mkdir -p build
        cd build
        go mod init caddy-build
        go get github.com/caddyserver/caddy/v2@latest
        cd ..

    - name: Install xcaddy
      run: |
        go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
        echo "$HOME/go/bin" >> $GITHUB_PATH

    - name: Get latest Caddy version
      id: get_version
      run: |
        VERSION=$(curl -s https://api.github.com/repos/caddyserver/caddy/releases/latest | jq -r .tag_name)
        echo "version=$VERSION" >> $GITHUB_ENV
        echo "Building Caddy version: $VERSION"

    - name: Build amd64
      run: |
        ARCH=amd64
        echo "Building for $ARCH architecture"
        xcaddy build ${{ env.version }} \
          --with github.com/caddyserver/forwardproxy@caddy2=github.com/klzgrad/forwardproxy@naive
        tar -czvf caddy-${ARCH}-${{ env.version }}.tar.gz caddy

    - name: Build arm64
      env:
        GOOS: linux
        GOARCH: arm64
      run: |
        ARCH=arm64
        echo "Building for $ARCH architecture"
        xcaddy build ${{ env.version }} \
          --with github.com/caddyserver/forwardproxy@caddy2=github.com/klzgrad/forwardproxy@naive
        tar -czvf caddy-${ARCH}-${{ env.version }}.tar.gz caddy

    - name: Generate SHA256 checksums
      run: |
        sha256sum caddy-amd64-${{ env.version }}.tar.gz > caddy-amd64-${{ env.version }}.sha256
        sha256sum caddy-arm64-${{ env.version }}.tar.gz > caddy-arm64-${{ env.version }}.sha256

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        body: |
          ### caddy-forwardproxy-naïve
        files: |
          caddy-amd64-${{ env.version }}.tar.gz
          caddy-arm64-${{ env.version }}.tar.gz
          caddy-amd64-${{ env.version }}.sha256
          caddy-arm64-${{ env.version }}.sha256