name: Build and Release Caddy

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [amd64, arm64]
        include:
          - arch: amd64
            goarch: amd64
          - arch: arm64
            goarch: arm64

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: stable
        cache: false

    - name: Install xcaddy
      run: |
        go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

    - name: Set version from tag
      id: get_version
      run: |
        VERSION=${{ github.ref_name }}
        echo "version=$VERSION" >> $GITHUB_ENV
        echo "clean_version=${VERSION#v}" >> $GITHUB_ENV
        echo "Building Caddy version: $VERSION"

    - name: Build Caddy (${{ matrix.arch }})
      env:
        GOOS: linux
        GOARCH: ${{ matrix.goarch }}
      run: |
        echo "Building for $GOARCH architecture"
        xcaddy build ${{ env.version }} \
          --with github.com/caddyserver/forwardproxy@caddy2=github.com/klzgrad/forwardproxy@naive
        test -f caddy && chmod +x caddy || (echo "Caddy build failed" && exit 1)
        tar -czvf caddy_${{ env.clean_version }}_linux_${{ matrix.arch }}.tar.gz caddy

    - name: Generate checksum
      run: |
        sha256sum caddy_${{ env.clean_version }}_linux_${{ matrix.arch }}.tar.gz > caddy_${{ env.clean_version }}_linux_${{ matrix.arch }}.sha256

    - name: Upload assets to release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: ${{ github.ref_name }}
        body: |
          ### caddy-forwardproxy-naïve
        files: |
          caddy_${{ env.clean_version }}_linux_${{ matrix.arch }}.tar.gz
          caddy_${{ env.clean_version }}_linux_${{ matrix.arch }}.sha256
